// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: driver_protocol.proto
// Original file comments:
//
// Copyright (c) Roc Streaming authors
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
//
#ifndef GRPC_driver_5fprotocol_2eproto__INCLUDED
#define GRPC_driver_5fprotocol_2eproto__INCLUDED

#include "driver_protocol.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace rvpb {

// RPC interface for Roc Virtual Audio Device driver.
class RvDriver final {
 public:
  static constexpr char const* service_full_name() {
    return "rvpb.RvDriver";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Check driver presence.
    // This command does nothing and just returns success.
    virtual ::grpc::Status ping(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::rvpb::RvNone* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvNone>> Asyncping(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvNone>>(AsyncpingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvNone>> PrepareAsyncping(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvNone>>(PrepareAsyncpingRaw(context, request, cq));
    }
    // Get driver info.
    virtual ::grpc::Status driver_info(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::rvpb::RvDriverInfo* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvDriverInfo>> Asyncdriver_info(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvDriverInfo>>(Asyncdriver_infoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvDriverInfo>> PrepareAsyncdriver_info(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvDriverInfo>>(PrepareAsyncdriver_infoRaw(context, request, cq));
    }
    // Stream driver logs to client.
    // Logs are duplicated to all clients that want to stream them.
    // Logs are also duplicated to syslog.
    std::unique_ptr< ::grpc::ClientReaderInterface< ::rvpb::RvLogEntry>> stream_logs(::grpc::ClientContext* context, const ::rvpb::RvNone& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::rvpb::RvLogEntry>>(stream_logsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::rvpb::RvLogEntry>> Asyncstream_logs(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::rvpb::RvLogEntry>>(Asyncstream_logsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::rvpb::RvLogEntry>> PrepareAsyncstream_logs(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::rvpb::RvLogEntry>>(PrepareAsyncstream_logsRaw(context, request, cq));
    }
    // Get info for all virtual devices.
    virtual ::grpc::Status get_all_devices(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::rvpb::RvDeviceList* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvDeviceList>> Asyncget_all_devices(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvDeviceList>>(Asyncget_all_devicesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvDeviceList>> PrepareAsyncget_all_devices(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvDeviceList>>(PrepareAsyncget_all_devicesRaw(context, request, cq));
    }
    // Get info for one virtual device.
    // Device can be selected by index or UID.
    virtual ::grpc::Status get_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector& request, ::rvpb::RvDeviceInfo* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvDeviceInfo>> Asyncget_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvDeviceInfo>>(Asyncget_deviceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvDeviceInfo>> PrepareAsyncget_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvDeviceInfo>>(PrepareAsyncget_deviceRaw(context, request, cq));
    }
    // Create new virtual device.
    // Returns updated device info with all fields set.
    virtual ::grpc::Status add_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceInfo& request, ::rvpb::RvDeviceInfo* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvDeviceInfo>> Asyncadd_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvDeviceInfo>>(Asyncadd_deviceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvDeviceInfo>> PrepareAsyncadd_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvDeviceInfo>>(PrepareAsyncadd_deviceRaw(context, request, cq));
    }
    // Delete virtual device.
    // Device can be selected by index or UID.
    virtual ::grpc::Status delete_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector& request, ::rvpb::RvNone* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvNone>> Asyncdelete_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvNone>>(Asyncdelete_deviceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvNone>> PrepareAsyncdelete_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvNone>>(PrepareAsyncdelete_deviceRaw(context, request, cq));
    }
    // Bind device to local endpoint.
    virtual ::grpc::Status bind(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest& request, ::rvpb::RvEndpointInfo* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvEndpointInfo>> Asyncbind(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvEndpointInfo>>(AsyncbindRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvEndpointInfo>> PrepareAsyncbind(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvEndpointInfo>>(PrepareAsyncbindRaw(context, request, cq));
    }
    // Connect device to remote endpoint.
    virtual ::grpc::Status connect(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest& request, ::rvpb::RvEndpointInfo* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvEndpointInfo>> Asyncconnect(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvEndpointInfo>>(AsyncconnectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvEndpointInfo>> PrepareAsyncconnect(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvEndpointInfo>>(PrepareAsyncconnectRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Check driver presence.
      // This command does nothing and just returns success.
      virtual void ping(::grpc::ClientContext* context, const ::rvpb::RvNone* request, ::rvpb::RvNone* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ping(::grpc::ClientContext* context, const ::rvpb::RvNone* request, ::rvpb::RvNone* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Get driver info.
      virtual void driver_info(::grpc::ClientContext* context, const ::rvpb::RvNone* request, ::rvpb::RvDriverInfo* response, std::function<void(::grpc::Status)>) = 0;
      virtual void driver_info(::grpc::ClientContext* context, const ::rvpb::RvNone* request, ::rvpb::RvDriverInfo* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Stream driver logs to client.
      // Logs are duplicated to all clients that want to stream them.
      // Logs are also duplicated to syslog.
      virtual void stream_logs(::grpc::ClientContext* context, const ::rvpb::RvNone* request, ::grpc::ClientReadReactor< ::rvpb::RvLogEntry>* reactor) = 0;
      // Get info for all virtual devices.
      virtual void get_all_devices(::grpc::ClientContext* context, const ::rvpb::RvNone* request, ::rvpb::RvDeviceList* response, std::function<void(::grpc::Status)>) = 0;
      virtual void get_all_devices(::grpc::ClientContext* context, const ::rvpb::RvNone* request, ::rvpb::RvDeviceList* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Get info for one virtual device.
      // Device can be selected by index or UID.
      virtual void get_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector* request, ::rvpb::RvDeviceInfo* response, std::function<void(::grpc::Status)>) = 0;
      virtual void get_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector* request, ::rvpb::RvDeviceInfo* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Create new virtual device.
      // Returns updated device info with all fields set.
      virtual void add_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceInfo* request, ::rvpb::RvDeviceInfo* response, std::function<void(::grpc::Status)>) = 0;
      virtual void add_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceInfo* request, ::rvpb::RvDeviceInfo* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Delete virtual device.
      // Device can be selected by index or UID.
      virtual void delete_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector* request, ::rvpb::RvNone* response, std::function<void(::grpc::Status)>) = 0;
      virtual void delete_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector* request, ::rvpb::RvNone* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Bind device to local endpoint.
      virtual void bind(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest* request, ::rvpb::RvEndpointInfo* response, std::function<void(::grpc::Status)>) = 0;
      virtual void bind(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest* request, ::rvpb::RvEndpointInfo* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Connect device to remote endpoint.
      virtual void connect(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest* request, ::rvpb::RvEndpointInfo* response, std::function<void(::grpc::Status)>) = 0;
      virtual void connect(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest* request, ::rvpb::RvEndpointInfo* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvNone>* AsyncpingRaw(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvNone>* PrepareAsyncpingRaw(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvDriverInfo>* Asyncdriver_infoRaw(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvDriverInfo>* PrepareAsyncdriver_infoRaw(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::rvpb::RvLogEntry>* stream_logsRaw(::grpc::ClientContext* context, const ::rvpb::RvNone& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::rvpb::RvLogEntry>* Asyncstream_logsRaw(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::rvpb::RvLogEntry>* PrepareAsyncstream_logsRaw(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvDeviceList>* Asyncget_all_devicesRaw(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvDeviceList>* PrepareAsyncget_all_devicesRaw(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvDeviceInfo>* Asyncget_deviceRaw(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvDeviceInfo>* PrepareAsyncget_deviceRaw(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvDeviceInfo>* Asyncadd_deviceRaw(::grpc::ClientContext* context, const ::rvpb::RvDeviceInfo& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvDeviceInfo>* PrepareAsyncadd_deviceRaw(::grpc::ClientContext* context, const ::rvpb::RvDeviceInfo& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvNone>* Asyncdelete_deviceRaw(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvNone>* PrepareAsyncdelete_deviceRaw(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvEndpointInfo>* AsyncbindRaw(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvEndpointInfo>* PrepareAsyncbindRaw(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvEndpointInfo>* AsyncconnectRaw(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rvpb::RvEndpointInfo>* PrepareAsyncconnectRaw(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ping(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::rvpb::RvNone* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvNone>> Asyncping(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvNone>>(AsyncpingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvNone>> PrepareAsyncping(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvNone>>(PrepareAsyncpingRaw(context, request, cq));
    }
    ::grpc::Status driver_info(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::rvpb::RvDriverInfo* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvDriverInfo>> Asyncdriver_info(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvDriverInfo>>(Asyncdriver_infoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvDriverInfo>> PrepareAsyncdriver_info(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvDriverInfo>>(PrepareAsyncdriver_infoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::rvpb::RvLogEntry>> stream_logs(::grpc::ClientContext* context, const ::rvpb::RvNone& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::rvpb::RvLogEntry>>(stream_logsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::rvpb::RvLogEntry>> Asyncstream_logs(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::rvpb::RvLogEntry>>(Asyncstream_logsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::rvpb::RvLogEntry>> PrepareAsyncstream_logs(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::rvpb::RvLogEntry>>(PrepareAsyncstream_logsRaw(context, request, cq));
    }
    ::grpc::Status get_all_devices(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::rvpb::RvDeviceList* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvDeviceList>> Asyncget_all_devices(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvDeviceList>>(Asyncget_all_devicesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvDeviceList>> PrepareAsyncget_all_devices(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvDeviceList>>(PrepareAsyncget_all_devicesRaw(context, request, cq));
    }
    ::grpc::Status get_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector& request, ::rvpb::RvDeviceInfo* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvDeviceInfo>> Asyncget_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvDeviceInfo>>(Asyncget_deviceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvDeviceInfo>> PrepareAsyncget_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvDeviceInfo>>(PrepareAsyncget_deviceRaw(context, request, cq));
    }
    ::grpc::Status add_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceInfo& request, ::rvpb::RvDeviceInfo* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvDeviceInfo>> Asyncadd_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvDeviceInfo>>(Asyncadd_deviceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvDeviceInfo>> PrepareAsyncadd_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvDeviceInfo>>(PrepareAsyncadd_deviceRaw(context, request, cq));
    }
    ::grpc::Status delete_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector& request, ::rvpb::RvNone* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvNone>> Asyncdelete_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvNone>>(Asyncdelete_deviceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvNone>> PrepareAsyncdelete_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvNone>>(PrepareAsyncdelete_deviceRaw(context, request, cq));
    }
    ::grpc::Status bind(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest& request, ::rvpb::RvEndpointInfo* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvEndpointInfo>> Asyncbind(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvEndpointInfo>>(AsyncbindRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvEndpointInfo>> PrepareAsyncbind(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvEndpointInfo>>(PrepareAsyncbindRaw(context, request, cq));
    }
    ::grpc::Status connect(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest& request, ::rvpb::RvEndpointInfo* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvEndpointInfo>> Asyncconnect(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvEndpointInfo>>(AsyncconnectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvEndpointInfo>> PrepareAsyncconnect(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rvpb::RvEndpointInfo>>(PrepareAsyncconnectRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ping(::grpc::ClientContext* context, const ::rvpb::RvNone* request, ::rvpb::RvNone* response, std::function<void(::grpc::Status)>) override;
      void ping(::grpc::ClientContext* context, const ::rvpb::RvNone* request, ::rvpb::RvNone* response, ::grpc::ClientUnaryReactor* reactor) override;
      void driver_info(::grpc::ClientContext* context, const ::rvpb::RvNone* request, ::rvpb::RvDriverInfo* response, std::function<void(::grpc::Status)>) override;
      void driver_info(::grpc::ClientContext* context, const ::rvpb::RvNone* request, ::rvpb::RvDriverInfo* response, ::grpc::ClientUnaryReactor* reactor) override;
      void stream_logs(::grpc::ClientContext* context, const ::rvpb::RvNone* request, ::grpc::ClientReadReactor< ::rvpb::RvLogEntry>* reactor) override;
      void get_all_devices(::grpc::ClientContext* context, const ::rvpb::RvNone* request, ::rvpb::RvDeviceList* response, std::function<void(::grpc::Status)>) override;
      void get_all_devices(::grpc::ClientContext* context, const ::rvpb::RvNone* request, ::rvpb::RvDeviceList* response, ::grpc::ClientUnaryReactor* reactor) override;
      void get_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector* request, ::rvpb::RvDeviceInfo* response, std::function<void(::grpc::Status)>) override;
      void get_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector* request, ::rvpb::RvDeviceInfo* response, ::grpc::ClientUnaryReactor* reactor) override;
      void add_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceInfo* request, ::rvpb::RvDeviceInfo* response, std::function<void(::grpc::Status)>) override;
      void add_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceInfo* request, ::rvpb::RvDeviceInfo* response, ::grpc::ClientUnaryReactor* reactor) override;
      void delete_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector* request, ::rvpb::RvNone* response, std::function<void(::grpc::Status)>) override;
      void delete_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector* request, ::rvpb::RvNone* response, ::grpc::ClientUnaryReactor* reactor) override;
      void bind(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest* request, ::rvpb::RvEndpointInfo* response, std::function<void(::grpc::Status)>) override;
      void bind(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest* request, ::rvpb::RvEndpointInfo* response, ::grpc::ClientUnaryReactor* reactor) override;
      void connect(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest* request, ::rvpb::RvEndpointInfo* response, std::function<void(::grpc::Status)>) override;
      void connect(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest* request, ::rvpb::RvEndpointInfo* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::rvpb::RvNone>* AsyncpingRaw(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rvpb::RvNone>* PrepareAsyncpingRaw(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rvpb::RvDriverInfo>* Asyncdriver_infoRaw(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rvpb::RvDriverInfo>* PrepareAsyncdriver_infoRaw(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::rvpb::RvLogEntry>* stream_logsRaw(::grpc::ClientContext* context, const ::rvpb::RvNone& request) override;
    ::grpc::ClientAsyncReader< ::rvpb::RvLogEntry>* Asyncstream_logsRaw(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::rvpb::RvLogEntry>* PrepareAsyncstream_logsRaw(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rvpb::RvDeviceList>* Asyncget_all_devicesRaw(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rvpb::RvDeviceList>* PrepareAsyncget_all_devicesRaw(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rvpb::RvDeviceInfo>* Asyncget_deviceRaw(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rvpb::RvDeviceInfo>* PrepareAsyncget_deviceRaw(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rvpb::RvDeviceInfo>* Asyncadd_deviceRaw(::grpc::ClientContext* context, const ::rvpb::RvDeviceInfo& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rvpb::RvDeviceInfo>* PrepareAsyncadd_deviceRaw(::grpc::ClientContext* context, const ::rvpb::RvDeviceInfo& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rvpb::RvNone>* Asyncdelete_deviceRaw(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rvpb::RvNone>* PrepareAsyncdelete_deviceRaw(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rvpb::RvEndpointInfo>* AsyncbindRaw(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rvpb::RvEndpointInfo>* PrepareAsyncbindRaw(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rvpb::RvEndpointInfo>* AsyncconnectRaw(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rvpb::RvEndpointInfo>* PrepareAsyncconnectRaw(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ping_;
    const ::grpc::internal::RpcMethod rpcmethod_driver_info_;
    const ::grpc::internal::RpcMethod rpcmethod_stream_logs_;
    const ::grpc::internal::RpcMethod rpcmethod_get_all_devices_;
    const ::grpc::internal::RpcMethod rpcmethod_get_device_;
    const ::grpc::internal::RpcMethod rpcmethod_add_device_;
    const ::grpc::internal::RpcMethod rpcmethod_delete_device_;
    const ::grpc::internal::RpcMethod rpcmethod_bind_;
    const ::grpc::internal::RpcMethod rpcmethod_connect_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Check driver presence.
    // This command does nothing and just returns success.
    virtual ::grpc::Status ping(::grpc::ServerContext* context, const ::rvpb::RvNone* request, ::rvpb::RvNone* response);
    // Get driver info.
    virtual ::grpc::Status driver_info(::grpc::ServerContext* context, const ::rvpb::RvNone* request, ::rvpb::RvDriverInfo* response);
    // Stream driver logs to client.
    // Logs are duplicated to all clients that want to stream them.
    // Logs are also duplicated to syslog.
    virtual ::grpc::Status stream_logs(::grpc::ServerContext* context, const ::rvpb::RvNone* request, ::grpc::ServerWriter< ::rvpb::RvLogEntry>* writer);
    // Get info for all virtual devices.
    virtual ::grpc::Status get_all_devices(::grpc::ServerContext* context, const ::rvpb::RvNone* request, ::rvpb::RvDeviceList* response);
    // Get info for one virtual device.
    // Device can be selected by index or UID.
    virtual ::grpc::Status get_device(::grpc::ServerContext* context, const ::rvpb::RvDeviceSelector* request, ::rvpb::RvDeviceInfo* response);
    // Create new virtual device.
    // Returns updated device info with all fields set.
    virtual ::grpc::Status add_device(::grpc::ServerContext* context, const ::rvpb::RvDeviceInfo* request, ::rvpb::RvDeviceInfo* response);
    // Delete virtual device.
    // Device can be selected by index or UID.
    virtual ::grpc::Status delete_device(::grpc::ServerContext* context, const ::rvpb::RvDeviceSelector* request, ::rvpb::RvNone* response);
    // Bind device to local endpoint.
    virtual ::grpc::Status bind(::grpc::ServerContext* context, const ::rvpb::RvEndpointRequest* request, ::rvpb::RvEndpointInfo* response);
    // Connect device to remote endpoint.
    virtual ::grpc::Status connect(::grpc::ServerContext* context, const ::rvpb::RvEndpointRequest* request, ::rvpb::RvEndpointInfo* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ping() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ping(::grpc::ServerContext* /*context*/, const ::rvpb::RvNone* /*request*/, ::rvpb::RvNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestping(::grpc::ServerContext* context, ::rvpb::RvNone* request, ::grpc::ServerAsyncResponseWriter< ::rvpb::RvNone>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_driver_info : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_driver_info() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_driver_info() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status driver_info(::grpc::ServerContext* /*context*/, const ::rvpb::RvNone* /*request*/, ::rvpb::RvDriverInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestdriver_info(::grpc::ServerContext* context, ::rvpb::RvNone* request, ::grpc::ServerAsyncResponseWriter< ::rvpb::RvDriverInfo>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_stream_logs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_stream_logs() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_stream_logs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status stream_logs(::grpc::ServerContext* /*context*/, const ::rvpb::RvNone* /*request*/, ::grpc::ServerWriter< ::rvpb::RvLogEntry>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requeststream_logs(::grpc::ServerContext* context, ::rvpb::RvNone* request, ::grpc::ServerAsyncWriter< ::rvpb::RvLogEntry>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(2, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_get_all_devices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_get_all_devices() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_get_all_devices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_all_devices(::grpc::ServerContext* /*context*/, const ::rvpb::RvNone* /*request*/, ::rvpb::RvDeviceList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestget_all_devices(::grpc::ServerContext* context, ::rvpb::RvNone* request, ::grpc::ServerAsyncResponseWriter< ::rvpb::RvDeviceList>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_get_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_get_device() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_get_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_device(::grpc::ServerContext* /*context*/, const ::rvpb::RvDeviceSelector* /*request*/, ::rvpb::RvDeviceInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestget_device(::grpc::ServerContext* context, ::rvpb::RvDeviceSelector* request, ::grpc::ServerAsyncResponseWriter< ::rvpb::RvDeviceInfo>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_add_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_add_device() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_add_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status add_device(::grpc::ServerContext* /*context*/, const ::rvpb::RvDeviceInfo* /*request*/, ::rvpb::RvDeviceInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestadd_device(::grpc::ServerContext* context, ::rvpb::RvDeviceInfo* request, ::grpc::ServerAsyncResponseWriter< ::rvpb::RvDeviceInfo>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_delete_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_delete_device() {
      ::grpc::Service::MarkMethodAsync(6);
    }
    ~WithAsyncMethod_delete_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status delete_device(::grpc::ServerContext* /*context*/, const ::rvpb::RvDeviceSelector* /*request*/, ::rvpb::RvNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestdelete_device(::grpc::ServerContext* context, ::rvpb::RvDeviceSelector* request, ::grpc::ServerAsyncResponseWriter< ::rvpb::RvNone>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(6, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_bind : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_bind() {
      ::grpc::Service::MarkMethodAsync(7);
    }
    ~WithAsyncMethod_bind() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status bind(::grpc::ServerContext* /*context*/, const ::rvpb::RvEndpointRequest* /*request*/, ::rvpb::RvEndpointInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestbind(::grpc::ServerContext* context, ::rvpb::RvEndpointRequest* request, ::grpc::ServerAsyncResponseWriter< ::rvpb::RvEndpointInfo>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(7, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_connect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_connect() {
      ::grpc::Service::MarkMethodAsync(8);
    }
    ~WithAsyncMethod_connect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status connect(::grpc::ServerContext* /*context*/, const ::rvpb::RvEndpointRequest* /*request*/, ::rvpb::RvEndpointInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestconnect(::grpc::ServerContext* context, ::rvpb::RvEndpointRequest* request, ::grpc::ServerAsyncResponseWriter< ::rvpb::RvEndpointInfo>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(8, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ping<WithAsyncMethod_driver_info<WithAsyncMethod_stream_logs<WithAsyncMethod_get_all_devices<WithAsyncMethod_get_device<WithAsyncMethod_add_device<WithAsyncMethod_delete_device<WithAsyncMethod_bind<WithAsyncMethod_connect<Service > > > > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ping() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::rvpb::RvNone, ::rvpb::RvNone>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rvpb::RvNone* request, ::rvpb::RvNone* response) { return this->ping(context, request, response); }));}
    void SetMessageAllocatorFor_ping(
        ::grpc::MessageAllocator< ::rvpb::RvNone, ::rvpb::RvNone>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rvpb::RvNone, ::rvpb::RvNone>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ping(::grpc::ServerContext* /*context*/, const ::rvpb::RvNone* /*request*/, ::rvpb::RvNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ping(
      ::grpc::CallbackServerContext* /*context*/, const ::rvpb::RvNone* /*request*/, ::rvpb::RvNone* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_driver_info : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_driver_info() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::rvpb::RvNone, ::rvpb::RvDriverInfo>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rvpb::RvNone* request, ::rvpb::RvDriverInfo* response) { return this->driver_info(context, request, response); }));}
    void SetMessageAllocatorFor_driver_info(
        ::grpc::MessageAllocator< ::rvpb::RvNone, ::rvpb::RvDriverInfo>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rvpb::RvNone, ::rvpb::RvDriverInfo>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_driver_info() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status driver_info(::grpc::ServerContext* /*context*/, const ::rvpb::RvNone* /*request*/, ::rvpb::RvDriverInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* driver_info(
      ::grpc::CallbackServerContext* /*context*/, const ::rvpb::RvNone* /*request*/, ::rvpb::RvDriverInfo* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_stream_logs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_stream_logs() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackServerStreamingHandler< ::rvpb::RvNone, ::rvpb::RvLogEntry>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rvpb::RvNone* request) { return this->stream_logs(context, request); }));
    }
    ~WithCallbackMethod_stream_logs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status stream_logs(::grpc::ServerContext* /*context*/, const ::rvpb::RvNone* /*request*/, ::grpc::ServerWriter< ::rvpb::RvLogEntry>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::rvpb::RvLogEntry>* stream_logs(
      ::grpc::CallbackServerContext* /*context*/, const ::rvpb::RvNone* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_get_all_devices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_get_all_devices() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::rvpb::RvNone, ::rvpb::RvDeviceList>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rvpb::RvNone* request, ::rvpb::RvDeviceList* response) { return this->get_all_devices(context, request, response); }));}
    void SetMessageAllocatorFor_get_all_devices(
        ::grpc::MessageAllocator< ::rvpb::RvNone, ::rvpb::RvDeviceList>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rvpb::RvNone, ::rvpb::RvDeviceList>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_get_all_devices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_all_devices(::grpc::ServerContext* /*context*/, const ::rvpb::RvNone* /*request*/, ::rvpb::RvDeviceList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* get_all_devices(
      ::grpc::CallbackServerContext* /*context*/, const ::rvpb::RvNone* /*request*/, ::rvpb::RvDeviceList* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_get_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_get_device() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::rvpb::RvDeviceSelector, ::rvpb::RvDeviceInfo>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rvpb::RvDeviceSelector* request, ::rvpb::RvDeviceInfo* response) { return this->get_device(context, request, response); }));}
    void SetMessageAllocatorFor_get_device(
        ::grpc::MessageAllocator< ::rvpb::RvDeviceSelector, ::rvpb::RvDeviceInfo>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rvpb::RvDeviceSelector, ::rvpb::RvDeviceInfo>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_get_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_device(::grpc::ServerContext* /*context*/, const ::rvpb::RvDeviceSelector* /*request*/, ::rvpb::RvDeviceInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* get_device(
      ::grpc::CallbackServerContext* /*context*/, const ::rvpb::RvDeviceSelector* /*request*/, ::rvpb::RvDeviceInfo* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_add_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_add_device() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::rvpb::RvDeviceInfo, ::rvpb::RvDeviceInfo>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rvpb::RvDeviceInfo* request, ::rvpb::RvDeviceInfo* response) { return this->add_device(context, request, response); }));}
    void SetMessageAllocatorFor_add_device(
        ::grpc::MessageAllocator< ::rvpb::RvDeviceInfo, ::rvpb::RvDeviceInfo>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rvpb::RvDeviceInfo, ::rvpb::RvDeviceInfo>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_add_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status add_device(::grpc::ServerContext* /*context*/, const ::rvpb::RvDeviceInfo* /*request*/, ::rvpb::RvDeviceInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* add_device(
      ::grpc::CallbackServerContext* /*context*/, const ::rvpb::RvDeviceInfo* /*request*/, ::rvpb::RvDeviceInfo* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_delete_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_delete_device() {
      ::grpc::Service::MarkMethodCallback(6,
          new ::grpc::internal::CallbackUnaryHandler< ::rvpb::RvDeviceSelector, ::rvpb::RvNone>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rvpb::RvDeviceSelector* request, ::rvpb::RvNone* response) { return this->delete_device(context, request, response); }));}
    void SetMessageAllocatorFor_delete_device(
        ::grpc::MessageAllocator< ::rvpb::RvDeviceSelector, ::rvpb::RvNone>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(6);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rvpb::RvDeviceSelector, ::rvpb::RvNone>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_delete_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status delete_device(::grpc::ServerContext* /*context*/, const ::rvpb::RvDeviceSelector* /*request*/, ::rvpb::RvNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* delete_device(
      ::grpc::CallbackServerContext* /*context*/, const ::rvpb::RvDeviceSelector* /*request*/, ::rvpb::RvNone* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_bind : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_bind() {
      ::grpc::Service::MarkMethodCallback(7,
          new ::grpc::internal::CallbackUnaryHandler< ::rvpb::RvEndpointRequest, ::rvpb::RvEndpointInfo>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rvpb::RvEndpointRequest* request, ::rvpb::RvEndpointInfo* response) { return this->bind(context, request, response); }));}
    void SetMessageAllocatorFor_bind(
        ::grpc::MessageAllocator< ::rvpb::RvEndpointRequest, ::rvpb::RvEndpointInfo>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(7);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rvpb::RvEndpointRequest, ::rvpb::RvEndpointInfo>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_bind() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status bind(::grpc::ServerContext* /*context*/, const ::rvpb::RvEndpointRequest* /*request*/, ::rvpb::RvEndpointInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* bind(
      ::grpc::CallbackServerContext* /*context*/, const ::rvpb::RvEndpointRequest* /*request*/, ::rvpb::RvEndpointInfo* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_connect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_connect() {
      ::grpc::Service::MarkMethodCallback(8,
          new ::grpc::internal::CallbackUnaryHandler< ::rvpb::RvEndpointRequest, ::rvpb::RvEndpointInfo>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rvpb::RvEndpointRequest* request, ::rvpb::RvEndpointInfo* response) { return this->connect(context, request, response); }));}
    void SetMessageAllocatorFor_connect(
        ::grpc::MessageAllocator< ::rvpb::RvEndpointRequest, ::rvpb::RvEndpointInfo>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(8);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rvpb::RvEndpointRequest, ::rvpb::RvEndpointInfo>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_connect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status connect(::grpc::ServerContext* /*context*/, const ::rvpb::RvEndpointRequest* /*request*/, ::rvpb::RvEndpointInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* connect(
      ::grpc::CallbackServerContext* /*context*/, const ::rvpb::RvEndpointRequest* /*request*/, ::rvpb::RvEndpointInfo* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ping<WithCallbackMethod_driver_info<WithCallbackMethod_stream_logs<WithCallbackMethod_get_all_devices<WithCallbackMethod_get_device<WithCallbackMethod_add_device<WithCallbackMethod_delete_device<WithCallbackMethod_bind<WithCallbackMethod_connect<Service > > > > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ping() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ping(::grpc::ServerContext* /*context*/, const ::rvpb::RvNone* /*request*/, ::rvpb::RvNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_driver_info : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_driver_info() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_driver_info() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status driver_info(::grpc::ServerContext* /*context*/, const ::rvpb::RvNone* /*request*/, ::rvpb::RvDriverInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_stream_logs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_stream_logs() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_stream_logs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status stream_logs(::grpc::ServerContext* /*context*/, const ::rvpb::RvNone* /*request*/, ::grpc::ServerWriter< ::rvpb::RvLogEntry>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_get_all_devices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_get_all_devices() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_get_all_devices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_all_devices(::grpc::ServerContext* /*context*/, const ::rvpb::RvNone* /*request*/, ::rvpb::RvDeviceList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_get_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_get_device() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_get_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_device(::grpc::ServerContext* /*context*/, const ::rvpb::RvDeviceSelector* /*request*/, ::rvpb::RvDeviceInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_add_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_add_device() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_add_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status add_device(::grpc::ServerContext* /*context*/, const ::rvpb::RvDeviceInfo* /*request*/, ::rvpb::RvDeviceInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_delete_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_delete_device() {
      ::grpc::Service::MarkMethodGeneric(6);
    }
    ~WithGenericMethod_delete_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status delete_device(::grpc::ServerContext* /*context*/, const ::rvpb::RvDeviceSelector* /*request*/, ::rvpb::RvNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_bind : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_bind() {
      ::grpc::Service::MarkMethodGeneric(7);
    }
    ~WithGenericMethod_bind() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status bind(::grpc::ServerContext* /*context*/, const ::rvpb::RvEndpointRequest* /*request*/, ::rvpb::RvEndpointInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_connect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_connect() {
      ::grpc::Service::MarkMethodGeneric(8);
    }
    ~WithGenericMethod_connect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status connect(::grpc::ServerContext* /*context*/, const ::rvpb::RvEndpointRequest* /*request*/, ::rvpb::RvEndpointInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ping() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ping(::grpc::ServerContext* /*context*/, const ::rvpb::RvNone* /*request*/, ::rvpb::RvNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestping(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_driver_info : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_driver_info() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_driver_info() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status driver_info(::grpc::ServerContext* /*context*/, const ::rvpb::RvNone* /*request*/, ::rvpb::RvDriverInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestdriver_info(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_stream_logs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_stream_logs() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_stream_logs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status stream_logs(::grpc::ServerContext* /*context*/, const ::rvpb::RvNone* /*request*/, ::grpc::ServerWriter< ::rvpb::RvLogEntry>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requeststream_logs(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(2, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_get_all_devices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_get_all_devices() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_get_all_devices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_all_devices(::grpc::ServerContext* /*context*/, const ::rvpb::RvNone* /*request*/, ::rvpb::RvDeviceList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestget_all_devices(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_get_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_get_device() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_get_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_device(::grpc::ServerContext* /*context*/, const ::rvpb::RvDeviceSelector* /*request*/, ::rvpb::RvDeviceInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestget_device(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_add_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_add_device() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_add_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status add_device(::grpc::ServerContext* /*context*/, const ::rvpb::RvDeviceInfo* /*request*/, ::rvpb::RvDeviceInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestadd_device(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_delete_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_delete_device() {
      ::grpc::Service::MarkMethodRaw(6);
    }
    ~WithRawMethod_delete_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status delete_device(::grpc::ServerContext* /*context*/, const ::rvpb::RvDeviceSelector* /*request*/, ::rvpb::RvNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestdelete_device(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(6, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_bind : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_bind() {
      ::grpc::Service::MarkMethodRaw(7);
    }
    ~WithRawMethod_bind() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status bind(::grpc::ServerContext* /*context*/, const ::rvpb::RvEndpointRequest* /*request*/, ::rvpb::RvEndpointInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestbind(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(7, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_connect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_connect() {
      ::grpc::Service::MarkMethodRaw(8);
    }
    ~WithRawMethod_connect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status connect(::grpc::ServerContext* /*context*/, const ::rvpb::RvEndpointRequest* /*request*/, ::rvpb::RvEndpointInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestconnect(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(8, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ping() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ping(context, request, response); }));
    }
    ~WithRawCallbackMethod_ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ping(::grpc::ServerContext* /*context*/, const ::rvpb::RvNone* /*request*/, ::rvpb::RvNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ping(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_driver_info : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_driver_info() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->driver_info(context, request, response); }));
    }
    ~WithRawCallbackMethod_driver_info() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status driver_info(::grpc::ServerContext* /*context*/, const ::rvpb::RvNone* /*request*/, ::rvpb::RvDriverInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* driver_info(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_stream_logs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_stream_logs() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->stream_logs(context, request); }));
    }
    ~WithRawCallbackMethod_stream_logs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status stream_logs(::grpc::ServerContext* /*context*/, const ::rvpb::RvNone* /*request*/, ::grpc::ServerWriter< ::rvpb::RvLogEntry>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* stream_logs(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_get_all_devices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_get_all_devices() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->get_all_devices(context, request, response); }));
    }
    ~WithRawCallbackMethod_get_all_devices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_all_devices(::grpc::ServerContext* /*context*/, const ::rvpb::RvNone* /*request*/, ::rvpb::RvDeviceList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* get_all_devices(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_get_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_get_device() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->get_device(context, request, response); }));
    }
    ~WithRawCallbackMethod_get_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_device(::grpc::ServerContext* /*context*/, const ::rvpb::RvDeviceSelector* /*request*/, ::rvpb::RvDeviceInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* get_device(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_add_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_add_device() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->add_device(context, request, response); }));
    }
    ~WithRawCallbackMethod_add_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status add_device(::grpc::ServerContext* /*context*/, const ::rvpb::RvDeviceInfo* /*request*/, ::rvpb::RvDeviceInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* add_device(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_delete_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_delete_device() {
      ::grpc::Service::MarkMethodRawCallback(6,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->delete_device(context, request, response); }));
    }
    ~WithRawCallbackMethod_delete_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status delete_device(::grpc::ServerContext* /*context*/, const ::rvpb::RvDeviceSelector* /*request*/, ::rvpb::RvNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* delete_device(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_bind : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_bind() {
      ::grpc::Service::MarkMethodRawCallback(7,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->bind(context, request, response); }));
    }
    ~WithRawCallbackMethod_bind() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status bind(::grpc::ServerContext* /*context*/, const ::rvpb::RvEndpointRequest* /*request*/, ::rvpb::RvEndpointInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* bind(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_connect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_connect() {
      ::grpc::Service::MarkMethodRawCallback(8,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->connect(context, request, response); }));
    }
    ~WithRawCallbackMethod_connect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status connect(::grpc::ServerContext* /*context*/, const ::rvpb::RvEndpointRequest* /*request*/, ::rvpb::RvEndpointInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* connect(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ping() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rvpb::RvNone, ::rvpb::RvNone>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rvpb::RvNone, ::rvpb::RvNone>* streamer) {
                       return this->Streamedping(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ping(::grpc::ServerContext* /*context*/, const ::rvpb::RvNone* /*request*/, ::rvpb::RvNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedping(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rvpb::RvNone,::rvpb::RvNone>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_driver_info : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_driver_info() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rvpb::RvNone, ::rvpb::RvDriverInfo>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rvpb::RvNone, ::rvpb::RvDriverInfo>* streamer) {
                       return this->Streameddriver_info(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_driver_info() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status driver_info(::grpc::ServerContext* /*context*/, const ::rvpb::RvNone* /*request*/, ::rvpb::RvDriverInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streameddriver_info(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rvpb::RvNone,::rvpb::RvDriverInfo>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_get_all_devices : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_get_all_devices() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rvpb::RvNone, ::rvpb::RvDeviceList>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rvpb::RvNone, ::rvpb::RvDeviceList>* streamer) {
                       return this->Streamedget_all_devices(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_get_all_devices() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status get_all_devices(::grpc::ServerContext* /*context*/, const ::rvpb::RvNone* /*request*/, ::rvpb::RvDeviceList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedget_all_devices(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rvpb::RvNone,::rvpb::RvDeviceList>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_get_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_get_device() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rvpb::RvDeviceSelector, ::rvpb::RvDeviceInfo>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rvpb::RvDeviceSelector, ::rvpb::RvDeviceInfo>* streamer) {
                       return this->Streamedget_device(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_get_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status get_device(::grpc::ServerContext* /*context*/, const ::rvpb::RvDeviceSelector* /*request*/, ::rvpb::RvDeviceInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedget_device(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rvpb::RvDeviceSelector,::rvpb::RvDeviceInfo>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_add_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_add_device() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rvpb::RvDeviceInfo, ::rvpb::RvDeviceInfo>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rvpb::RvDeviceInfo, ::rvpb::RvDeviceInfo>* streamer) {
                       return this->Streamedadd_device(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_add_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status add_device(::grpc::ServerContext* /*context*/, const ::rvpb::RvDeviceInfo* /*request*/, ::rvpb::RvDeviceInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedadd_device(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rvpb::RvDeviceInfo,::rvpb::RvDeviceInfo>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_delete_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_delete_device() {
      ::grpc::Service::MarkMethodStreamed(6,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rvpb::RvDeviceSelector, ::rvpb::RvNone>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rvpb::RvDeviceSelector, ::rvpb::RvNone>* streamer) {
                       return this->Streameddelete_device(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_delete_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status delete_device(::grpc::ServerContext* /*context*/, const ::rvpb::RvDeviceSelector* /*request*/, ::rvpb::RvNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streameddelete_device(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rvpb::RvDeviceSelector,::rvpb::RvNone>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_bind : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_bind() {
      ::grpc::Service::MarkMethodStreamed(7,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rvpb::RvEndpointRequest, ::rvpb::RvEndpointInfo>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rvpb::RvEndpointRequest, ::rvpb::RvEndpointInfo>* streamer) {
                       return this->Streamedbind(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_bind() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status bind(::grpc::ServerContext* /*context*/, const ::rvpb::RvEndpointRequest* /*request*/, ::rvpb::RvEndpointInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedbind(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rvpb::RvEndpointRequest,::rvpb::RvEndpointInfo>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_connect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_connect() {
      ::grpc::Service::MarkMethodStreamed(8,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rvpb::RvEndpointRequest, ::rvpb::RvEndpointInfo>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rvpb::RvEndpointRequest, ::rvpb::RvEndpointInfo>* streamer) {
                       return this->Streamedconnect(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_connect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status connect(::grpc::ServerContext* /*context*/, const ::rvpb::RvEndpointRequest* /*request*/, ::rvpb::RvEndpointInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedconnect(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rvpb::RvEndpointRequest,::rvpb::RvEndpointInfo>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ping<WithStreamedUnaryMethod_driver_info<WithStreamedUnaryMethod_get_all_devices<WithStreamedUnaryMethod_get_device<WithStreamedUnaryMethod_add_device<WithStreamedUnaryMethod_delete_device<WithStreamedUnaryMethod_bind<WithStreamedUnaryMethod_connect<Service > > > > > > > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_stream_logs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_stream_logs() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::rvpb::RvNone, ::rvpb::RvLogEntry>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::rvpb::RvNone, ::rvpb::RvLogEntry>* streamer) {
                       return this->Streamedstream_logs(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_stream_logs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status stream_logs(::grpc::ServerContext* /*context*/, const ::rvpb::RvNone* /*request*/, ::grpc::ServerWriter< ::rvpb::RvLogEntry>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status Streamedstream_logs(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::rvpb::RvNone,::rvpb::RvLogEntry>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_stream_logs<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_ping<WithStreamedUnaryMethod_driver_info<WithSplitStreamingMethod_stream_logs<WithStreamedUnaryMethod_get_all_devices<WithStreamedUnaryMethod_get_device<WithStreamedUnaryMethod_add_device<WithStreamedUnaryMethod_delete_device<WithStreamedUnaryMethod_bind<WithStreamedUnaryMethod_connect<Service > > > > > > > > > StreamedService;
};

}  // namespace rvpb


#endif  // GRPC_driver_5fprotocol_2eproto__INCLUDED
