// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: driver_protocol.proto

#include "driver_protocol.pb.h"
#include "driver_protocol.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace rvpb {

static const char* RvDriver_method_names[] = {
  "/rvpb.RvDriver/ping",
  "/rvpb.RvDriver/driver_info",
  "/rvpb.RvDriver/stream_logs",
  "/rvpb.RvDriver/get_all_devices",
  "/rvpb.RvDriver/get_device",
  "/rvpb.RvDriver/add_device",
  "/rvpb.RvDriver/delete_device",
  "/rvpb.RvDriver/toggle_device",
  "/rvpb.RvDriver/bind",
  "/rvpb.RvDriver/connect",
};

std::unique_ptr< RvDriver::Stub> RvDriver::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RvDriver::Stub> stub(new RvDriver::Stub(channel, options));
  return stub;
}

RvDriver::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ping_(RvDriver_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_driver_info_(RvDriver_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_stream_logs_(RvDriver_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_get_all_devices_(RvDriver_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_get_device_(RvDriver_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_add_device_(RvDriver_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_delete_device_(RvDriver_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_toggle_device_(RvDriver_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_bind_(RvDriver_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_connect_(RvDriver_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RvDriver::Stub::ping(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::rvpb::RvNone* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rvpb::RvNone, ::rvpb::RvNone, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ping_, context, request, response);
}

void RvDriver::Stub::async::ping(::grpc::ClientContext* context, const ::rvpb::RvNone* request, ::rvpb::RvNone* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rvpb::RvNone, ::rvpb::RvNone, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ping_, context, request, response, std::move(f));
}

void RvDriver::Stub::async::ping(::grpc::ClientContext* context, const ::rvpb::RvNone* request, ::rvpb::RvNone* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ping_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rvpb::RvNone>* RvDriver::Stub::PrepareAsyncpingRaw(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rvpb::RvNone, ::rvpb::RvNone, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ping_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rvpb::RvNone>* RvDriver::Stub::AsyncpingRaw(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncpingRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RvDriver::Stub::driver_info(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::rvpb::RvDriverInfo* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rvpb::RvNone, ::rvpb::RvDriverInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_driver_info_, context, request, response);
}

void RvDriver::Stub::async::driver_info(::grpc::ClientContext* context, const ::rvpb::RvNone* request, ::rvpb::RvDriverInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rvpb::RvNone, ::rvpb::RvDriverInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_driver_info_, context, request, response, std::move(f));
}

void RvDriver::Stub::async::driver_info(::grpc::ClientContext* context, const ::rvpb::RvNone* request, ::rvpb::RvDriverInfo* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_driver_info_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rvpb::RvDriverInfo>* RvDriver::Stub::PrepareAsyncdriver_infoRaw(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rvpb::RvDriverInfo, ::rvpb::RvNone, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_driver_info_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rvpb::RvDriverInfo>* RvDriver::Stub::Asyncdriver_infoRaw(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdriver_infoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::rvpb::RvLogEntry>* RvDriver::Stub::stream_logsRaw(::grpc::ClientContext* context, const ::rvpb::RvNone& request) {
  return ::grpc::internal::ClientReaderFactory< ::rvpb::RvLogEntry>::Create(channel_.get(), rpcmethod_stream_logs_, context, request);
}

void RvDriver::Stub::async::stream_logs(::grpc::ClientContext* context, const ::rvpb::RvNone* request, ::grpc::ClientReadReactor< ::rvpb::RvLogEntry>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::rvpb::RvLogEntry>::Create(stub_->channel_.get(), stub_->rpcmethod_stream_logs_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::rvpb::RvLogEntry>* RvDriver::Stub::Asyncstream_logsRaw(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::rvpb::RvLogEntry>::Create(channel_.get(), cq, rpcmethod_stream_logs_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::rvpb::RvLogEntry>* RvDriver::Stub::PrepareAsyncstream_logsRaw(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::rvpb::RvLogEntry>::Create(channel_.get(), cq, rpcmethod_stream_logs_, context, request, false, nullptr);
}

::grpc::Status RvDriver::Stub::get_all_devices(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::rvpb::RvDeviceList* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rvpb::RvNone, ::rvpb::RvDeviceList, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_get_all_devices_, context, request, response);
}

void RvDriver::Stub::async::get_all_devices(::grpc::ClientContext* context, const ::rvpb::RvNone* request, ::rvpb::RvDeviceList* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rvpb::RvNone, ::rvpb::RvDeviceList, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_get_all_devices_, context, request, response, std::move(f));
}

void RvDriver::Stub::async::get_all_devices(::grpc::ClientContext* context, const ::rvpb::RvNone* request, ::rvpb::RvDeviceList* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_get_all_devices_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rvpb::RvDeviceList>* RvDriver::Stub::PrepareAsyncget_all_devicesRaw(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rvpb::RvDeviceList, ::rvpb::RvNone, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_get_all_devices_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rvpb::RvDeviceList>* RvDriver::Stub::Asyncget_all_devicesRaw(::grpc::ClientContext* context, const ::rvpb::RvNone& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncget_all_devicesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RvDriver::Stub::get_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector& request, ::rvpb::RvDeviceInfo* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rvpb::RvDeviceSelector, ::rvpb::RvDeviceInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_get_device_, context, request, response);
}

void RvDriver::Stub::async::get_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector* request, ::rvpb::RvDeviceInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rvpb::RvDeviceSelector, ::rvpb::RvDeviceInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_get_device_, context, request, response, std::move(f));
}

void RvDriver::Stub::async::get_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector* request, ::rvpb::RvDeviceInfo* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_get_device_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rvpb::RvDeviceInfo>* RvDriver::Stub::PrepareAsyncget_deviceRaw(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rvpb::RvDeviceInfo, ::rvpb::RvDeviceSelector, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_get_device_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rvpb::RvDeviceInfo>* RvDriver::Stub::Asyncget_deviceRaw(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncget_deviceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RvDriver::Stub::add_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceInfo& request, ::rvpb::RvDeviceInfo* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rvpb::RvDeviceInfo, ::rvpb::RvDeviceInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_add_device_, context, request, response);
}

void RvDriver::Stub::async::add_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceInfo* request, ::rvpb::RvDeviceInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rvpb::RvDeviceInfo, ::rvpb::RvDeviceInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_add_device_, context, request, response, std::move(f));
}

void RvDriver::Stub::async::add_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceInfo* request, ::rvpb::RvDeviceInfo* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_add_device_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rvpb::RvDeviceInfo>* RvDriver::Stub::PrepareAsyncadd_deviceRaw(::grpc::ClientContext* context, const ::rvpb::RvDeviceInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rvpb::RvDeviceInfo, ::rvpb::RvDeviceInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_add_device_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rvpb::RvDeviceInfo>* RvDriver::Stub::Asyncadd_deviceRaw(::grpc::ClientContext* context, const ::rvpb::RvDeviceInfo& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncadd_deviceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RvDriver::Stub::delete_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector& request, ::rvpb::RvNone* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rvpb::RvDeviceSelector, ::rvpb::RvNone, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_delete_device_, context, request, response);
}

void RvDriver::Stub::async::delete_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector* request, ::rvpb::RvNone* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rvpb::RvDeviceSelector, ::rvpb::RvNone, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_delete_device_, context, request, response, std::move(f));
}

void RvDriver::Stub::async::delete_device(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector* request, ::rvpb::RvNone* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_delete_device_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rvpb::RvNone>* RvDriver::Stub::PrepareAsyncdelete_deviceRaw(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rvpb::RvNone, ::rvpb::RvDeviceSelector, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_delete_device_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rvpb::RvNone>* RvDriver::Stub::Asyncdelete_deviceRaw(::grpc::ClientContext* context, const ::rvpb::RvDeviceSelector& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdelete_deviceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RvDriver::Stub::toggle_device(::grpc::ClientContext* context, const ::rvpb::RvToggleRequest& request, ::rvpb::RvNone* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rvpb::RvToggleRequest, ::rvpb::RvNone, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_toggle_device_, context, request, response);
}

void RvDriver::Stub::async::toggle_device(::grpc::ClientContext* context, const ::rvpb::RvToggleRequest* request, ::rvpb::RvNone* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rvpb::RvToggleRequest, ::rvpb::RvNone, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_toggle_device_, context, request, response, std::move(f));
}

void RvDriver::Stub::async::toggle_device(::grpc::ClientContext* context, const ::rvpb::RvToggleRequest* request, ::rvpb::RvNone* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_toggle_device_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rvpb::RvNone>* RvDriver::Stub::PrepareAsynctoggle_deviceRaw(::grpc::ClientContext* context, const ::rvpb::RvToggleRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rvpb::RvNone, ::rvpb::RvToggleRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_toggle_device_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rvpb::RvNone>* RvDriver::Stub::Asynctoggle_deviceRaw(::grpc::ClientContext* context, const ::rvpb::RvToggleRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynctoggle_deviceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RvDriver::Stub::bind(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest& request, ::rvpb::RvEndpointInfo* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rvpb::RvEndpointRequest, ::rvpb::RvEndpointInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_bind_, context, request, response);
}

void RvDriver::Stub::async::bind(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest* request, ::rvpb::RvEndpointInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rvpb::RvEndpointRequest, ::rvpb::RvEndpointInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_bind_, context, request, response, std::move(f));
}

void RvDriver::Stub::async::bind(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest* request, ::rvpb::RvEndpointInfo* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_bind_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rvpb::RvEndpointInfo>* RvDriver::Stub::PrepareAsyncbindRaw(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rvpb::RvEndpointInfo, ::rvpb::RvEndpointRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_bind_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rvpb::RvEndpointInfo>* RvDriver::Stub::AsyncbindRaw(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncbindRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RvDriver::Stub::connect(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest& request, ::rvpb::RvEndpointInfo* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rvpb::RvEndpointRequest, ::rvpb::RvEndpointInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_connect_, context, request, response);
}

void RvDriver::Stub::async::connect(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest* request, ::rvpb::RvEndpointInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rvpb::RvEndpointRequest, ::rvpb::RvEndpointInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_connect_, context, request, response, std::move(f));
}

void RvDriver::Stub::async::connect(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest* request, ::rvpb::RvEndpointInfo* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_connect_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rvpb::RvEndpointInfo>* RvDriver::Stub::PrepareAsyncconnectRaw(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rvpb::RvEndpointInfo, ::rvpb::RvEndpointRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_connect_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rvpb::RvEndpointInfo>* RvDriver::Stub::AsyncconnectRaw(::grpc::ClientContext* context, const ::rvpb::RvEndpointRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncconnectRaw(context, request, cq);
  result->StartCall();
  return result;
}

RvDriver::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RvDriver_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RvDriver::Service, ::rvpb::RvNone, ::rvpb::RvNone, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RvDriver::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rvpb::RvNone* req,
             ::rvpb::RvNone* resp) {
               return service->ping(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RvDriver_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RvDriver::Service, ::rvpb::RvNone, ::rvpb::RvDriverInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RvDriver::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rvpb::RvNone* req,
             ::rvpb::RvDriverInfo* resp) {
               return service->driver_info(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RvDriver_method_names[2],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< RvDriver::Service, ::rvpb::RvNone, ::rvpb::RvLogEntry>(
          [](RvDriver::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rvpb::RvNone* req,
             ::grpc::ServerWriter<::rvpb::RvLogEntry>* writer) {
               return service->stream_logs(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RvDriver_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RvDriver::Service, ::rvpb::RvNone, ::rvpb::RvDeviceList, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RvDriver::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rvpb::RvNone* req,
             ::rvpb::RvDeviceList* resp) {
               return service->get_all_devices(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RvDriver_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RvDriver::Service, ::rvpb::RvDeviceSelector, ::rvpb::RvDeviceInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RvDriver::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rvpb::RvDeviceSelector* req,
             ::rvpb::RvDeviceInfo* resp) {
               return service->get_device(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RvDriver_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RvDriver::Service, ::rvpb::RvDeviceInfo, ::rvpb::RvDeviceInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RvDriver::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rvpb::RvDeviceInfo* req,
             ::rvpb::RvDeviceInfo* resp) {
               return service->add_device(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RvDriver_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RvDriver::Service, ::rvpb::RvDeviceSelector, ::rvpb::RvNone, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RvDriver::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rvpb::RvDeviceSelector* req,
             ::rvpb::RvNone* resp) {
               return service->delete_device(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RvDriver_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RvDriver::Service, ::rvpb::RvToggleRequest, ::rvpb::RvNone, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RvDriver::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rvpb::RvToggleRequest* req,
             ::rvpb::RvNone* resp) {
               return service->toggle_device(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RvDriver_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RvDriver::Service, ::rvpb::RvEndpointRequest, ::rvpb::RvEndpointInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RvDriver::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rvpb::RvEndpointRequest* req,
             ::rvpb::RvEndpointInfo* resp) {
               return service->bind(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RvDriver_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RvDriver::Service, ::rvpb::RvEndpointRequest, ::rvpb::RvEndpointInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RvDriver::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rvpb::RvEndpointRequest* req,
             ::rvpb::RvEndpointInfo* resp) {
               return service->connect(ctx, req, resp);
             }, this)));
}

RvDriver::Service::~Service() {
}

::grpc::Status RvDriver::Service::ping(::grpc::ServerContext* context, const ::rvpb::RvNone* request, ::rvpb::RvNone* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RvDriver::Service::driver_info(::grpc::ServerContext* context, const ::rvpb::RvNone* request, ::rvpb::RvDriverInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RvDriver::Service::stream_logs(::grpc::ServerContext* context, const ::rvpb::RvNone* request, ::grpc::ServerWriter< ::rvpb::RvLogEntry>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RvDriver::Service::get_all_devices(::grpc::ServerContext* context, const ::rvpb::RvNone* request, ::rvpb::RvDeviceList* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RvDriver::Service::get_device(::grpc::ServerContext* context, const ::rvpb::RvDeviceSelector* request, ::rvpb::RvDeviceInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RvDriver::Service::add_device(::grpc::ServerContext* context, const ::rvpb::RvDeviceInfo* request, ::rvpb::RvDeviceInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RvDriver::Service::delete_device(::grpc::ServerContext* context, const ::rvpb::RvDeviceSelector* request, ::rvpb::RvNone* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RvDriver::Service::toggle_device(::grpc::ServerContext* context, const ::rvpb::RvToggleRequest* request, ::rvpb::RvNone* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RvDriver::Service::bind(::grpc::ServerContext* context, const ::rvpb::RvEndpointRequest* request, ::rvpb::RvEndpointInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RvDriver::Service::connect(::grpc::ServerContext* context, const ::rvpb::RvEndpointRequest* request, ::rvpb::RvEndpointInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace rvpb

