// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: driver_protocol.proto
// Original file comments:
//
// Copyright (c) Roc Streaming authors
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
//
#ifndef GRPC_driver_5fprotocol_2eproto__INCLUDED
#define GRPC_driver_5fprotocol_2eproto__INCLUDED

#include "driver_protocol.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace rocvad {

class DriverProtocol final {
 public:
  static constexpr char const* service_full_name() {
    return "rocvad.DriverProtocol";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ping(::grpc::ClientContext* context, const ::rocvad::MesgNone& request, ::rocvad::MesgNone* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rocvad::MesgNone>> Asyncping(::grpc::ClientContext* context, const ::rocvad::MesgNone& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rocvad::MesgNone>>(AsyncpingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rocvad::MesgNone>> PrepareAsyncping(::grpc::ClientContext* context, const ::rocvad::MesgNone& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rocvad::MesgNone>>(PrepareAsyncpingRaw(context, request, cq));
    }
    virtual ::grpc::Status get_info(::grpc::ClientContext* context, const ::rocvad::MesgNone& request, ::rocvad::MesgInfo* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rocvad::MesgInfo>> Asyncget_info(::grpc::ClientContext* context, const ::rocvad::MesgNone& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rocvad::MesgInfo>>(Asyncget_infoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rocvad::MesgInfo>> PrepareAsyncget_info(::grpc::ClientContext* context, const ::rocvad::MesgNone& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rocvad::MesgInfo>>(PrepareAsyncget_infoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::rocvad::MesgLogEntry>> stream_logs(::grpc::ClientContext* context, const ::rocvad::MesgNone& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::rocvad::MesgLogEntry>>(stream_logsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::rocvad::MesgLogEntry>> Asyncstream_logs(::grpc::ClientContext* context, const ::rocvad::MesgNone& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::rocvad::MesgLogEntry>>(Asyncstream_logsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::rocvad::MesgLogEntry>> PrepareAsyncstream_logs(::grpc::ClientContext* context, const ::rocvad::MesgNone& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::rocvad::MesgLogEntry>>(PrepareAsyncstream_logsRaw(context, request, cq));
    }
    virtual ::grpc::Status add_device(::grpc::ClientContext* context, const ::rocvad::MesgAddDevice& request, ::rocvad::MesgNone* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rocvad::MesgNone>> Asyncadd_device(::grpc::ClientContext* context, const ::rocvad::MesgAddDevice& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rocvad::MesgNone>>(Asyncadd_deviceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rocvad::MesgNone>> PrepareAsyncadd_device(::grpc::ClientContext* context, const ::rocvad::MesgAddDevice& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rocvad::MesgNone>>(PrepareAsyncadd_deviceRaw(context, request, cq));
    }
    virtual ::grpc::Status delete_device(::grpc::ClientContext* context, const ::rocvad::MesgDeleteDevice& request, ::rocvad::MesgNone* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rocvad::MesgNone>> Asyncdelete_device(::grpc::ClientContext* context, const ::rocvad::MesgDeleteDevice& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rocvad::MesgNone>>(Asyncdelete_deviceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rocvad::MesgNone>> PrepareAsyncdelete_device(::grpc::ClientContext* context, const ::rocvad::MesgDeleteDevice& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rocvad::MesgNone>>(PrepareAsyncdelete_deviceRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void ping(::grpc::ClientContext* context, const ::rocvad::MesgNone* request, ::rocvad::MesgNone* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ping(::grpc::ClientContext* context, const ::rocvad::MesgNone* request, ::rocvad::MesgNone* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void get_info(::grpc::ClientContext* context, const ::rocvad::MesgNone* request, ::rocvad::MesgInfo* response, std::function<void(::grpc::Status)>) = 0;
      virtual void get_info(::grpc::ClientContext* context, const ::rocvad::MesgNone* request, ::rocvad::MesgInfo* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void stream_logs(::grpc::ClientContext* context, const ::rocvad::MesgNone* request, ::grpc::ClientReadReactor< ::rocvad::MesgLogEntry>* reactor) = 0;
      virtual void add_device(::grpc::ClientContext* context, const ::rocvad::MesgAddDevice* request, ::rocvad::MesgNone* response, std::function<void(::grpc::Status)>) = 0;
      virtual void add_device(::grpc::ClientContext* context, const ::rocvad::MesgAddDevice* request, ::rocvad::MesgNone* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void delete_device(::grpc::ClientContext* context, const ::rocvad::MesgDeleteDevice* request, ::rocvad::MesgNone* response, std::function<void(::grpc::Status)>) = 0;
      virtual void delete_device(::grpc::ClientContext* context, const ::rocvad::MesgDeleteDevice* request, ::rocvad::MesgNone* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rocvad::MesgNone>* AsyncpingRaw(::grpc::ClientContext* context, const ::rocvad::MesgNone& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rocvad::MesgNone>* PrepareAsyncpingRaw(::grpc::ClientContext* context, const ::rocvad::MesgNone& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rocvad::MesgInfo>* Asyncget_infoRaw(::grpc::ClientContext* context, const ::rocvad::MesgNone& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rocvad::MesgInfo>* PrepareAsyncget_infoRaw(::grpc::ClientContext* context, const ::rocvad::MesgNone& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::rocvad::MesgLogEntry>* stream_logsRaw(::grpc::ClientContext* context, const ::rocvad::MesgNone& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::rocvad::MesgLogEntry>* Asyncstream_logsRaw(::grpc::ClientContext* context, const ::rocvad::MesgNone& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::rocvad::MesgLogEntry>* PrepareAsyncstream_logsRaw(::grpc::ClientContext* context, const ::rocvad::MesgNone& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rocvad::MesgNone>* Asyncadd_deviceRaw(::grpc::ClientContext* context, const ::rocvad::MesgAddDevice& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rocvad::MesgNone>* PrepareAsyncadd_deviceRaw(::grpc::ClientContext* context, const ::rocvad::MesgAddDevice& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rocvad::MesgNone>* Asyncdelete_deviceRaw(::grpc::ClientContext* context, const ::rocvad::MesgDeleteDevice& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rocvad::MesgNone>* PrepareAsyncdelete_deviceRaw(::grpc::ClientContext* context, const ::rocvad::MesgDeleteDevice& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ping(::grpc::ClientContext* context, const ::rocvad::MesgNone& request, ::rocvad::MesgNone* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rocvad::MesgNone>> Asyncping(::grpc::ClientContext* context, const ::rocvad::MesgNone& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rocvad::MesgNone>>(AsyncpingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rocvad::MesgNone>> PrepareAsyncping(::grpc::ClientContext* context, const ::rocvad::MesgNone& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rocvad::MesgNone>>(PrepareAsyncpingRaw(context, request, cq));
    }
    ::grpc::Status get_info(::grpc::ClientContext* context, const ::rocvad::MesgNone& request, ::rocvad::MesgInfo* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rocvad::MesgInfo>> Asyncget_info(::grpc::ClientContext* context, const ::rocvad::MesgNone& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rocvad::MesgInfo>>(Asyncget_infoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rocvad::MesgInfo>> PrepareAsyncget_info(::grpc::ClientContext* context, const ::rocvad::MesgNone& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rocvad::MesgInfo>>(PrepareAsyncget_infoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::rocvad::MesgLogEntry>> stream_logs(::grpc::ClientContext* context, const ::rocvad::MesgNone& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::rocvad::MesgLogEntry>>(stream_logsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::rocvad::MesgLogEntry>> Asyncstream_logs(::grpc::ClientContext* context, const ::rocvad::MesgNone& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::rocvad::MesgLogEntry>>(Asyncstream_logsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::rocvad::MesgLogEntry>> PrepareAsyncstream_logs(::grpc::ClientContext* context, const ::rocvad::MesgNone& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::rocvad::MesgLogEntry>>(PrepareAsyncstream_logsRaw(context, request, cq));
    }
    ::grpc::Status add_device(::grpc::ClientContext* context, const ::rocvad::MesgAddDevice& request, ::rocvad::MesgNone* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rocvad::MesgNone>> Asyncadd_device(::grpc::ClientContext* context, const ::rocvad::MesgAddDevice& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rocvad::MesgNone>>(Asyncadd_deviceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rocvad::MesgNone>> PrepareAsyncadd_device(::grpc::ClientContext* context, const ::rocvad::MesgAddDevice& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rocvad::MesgNone>>(PrepareAsyncadd_deviceRaw(context, request, cq));
    }
    ::grpc::Status delete_device(::grpc::ClientContext* context, const ::rocvad::MesgDeleteDevice& request, ::rocvad::MesgNone* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rocvad::MesgNone>> Asyncdelete_device(::grpc::ClientContext* context, const ::rocvad::MesgDeleteDevice& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rocvad::MesgNone>>(Asyncdelete_deviceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rocvad::MesgNone>> PrepareAsyncdelete_device(::grpc::ClientContext* context, const ::rocvad::MesgDeleteDevice& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rocvad::MesgNone>>(PrepareAsyncdelete_deviceRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ping(::grpc::ClientContext* context, const ::rocvad::MesgNone* request, ::rocvad::MesgNone* response, std::function<void(::grpc::Status)>) override;
      void ping(::grpc::ClientContext* context, const ::rocvad::MesgNone* request, ::rocvad::MesgNone* response, ::grpc::ClientUnaryReactor* reactor) override;
      void get_info(::grpc::ClientContext* context, const ::rocvad::MesgNone* request, ::rocvad::MesgInfo* response, std::function<void(::grpc::Status)>) override;
      void get_info(::grpc::ClientContext* context, const ::rocvad::MesgNone* request, ::rocvad::MesgInfo* response, ::grpc::ClientUnaryReactor* reactor) override;
      void stream_logs(::grpc::ClientContext* context, const ::rocvad::MesgNone* request, ::grpc::ClientReadReactor< ::rocvad::MesgLogEntry>* reactor) override;
      void add_device(::grpc::ClientContext* context, const ::rocvad::MesgAddDevice* request, ::rocvad::MesgNone* response, std::function<void(::grpc::Status)>) override;
      void add_device(::grpc::ClientContext* context, const ::rocvad::MesgAddDevice* request, ::rocvad::MesgNone* response, ::grpc::ClientUnaryReactor* reactor) override;
      void delete_device(::grpc::ClientContext* context, const ::rocvad::MesgDeleteDevice* request, ::rocvad::MesgNone* response, std::function<void(::grpc::Status)>) override;
      void delete_device(::grpc::ClientContext* context, const ::rocvad::MesgDeleteDevice* request, ::rocvad::MesgNone* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::rocvad::MesgNone>* AsyncpingRaw(::grpc::ClientContext* context, const ::rocvad::MesgNone& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rocvad::MesgNone>* PrepareAsyncpingRaw(::grpc::ClientContext* context, const ::rocvad::MesgNone& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rocvad::MesgInfo>* Asyncget_infoRaw(::grpc::ClientContext* context, const ::rocvad::MesgNone& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rocvad::MesgInfo>* PrepareAsyncget_infoRaw(::grpc::ClientContext* context, const ::rocvad::MesgNone& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::rocvad::MesgLogEntry>* stream_logsRaw(::grpc::ClientContext* context, const ::rocvad::MesgNone& request) override;
    ::grpc::ClientAsyncReader< ::rocvad::MesgLogEntry>* Asyncstream_logsRaw(::grpc::ClientContext* context, const ::rocvad::MesgNone& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::rocvad::MesgLogEntry>* PrepareAsyncstream_logsRaw(::grpc::ClientContext* context, const ::rocvad::MesgNone& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rocvad::MesgNone>* Asyncadd_deviceRaw(::grpc::ClientContext* context, const ::rocvad::MesgAddDevice& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rocvad::MesgNone>* PrepareAsyncadd_deviceRaw(::grpc::ClientContext* context, const ::rocvad::MesgAddDevice& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rocvad::MesgNone>* Asyncdelete_deviceRaw(::grpc::ClientContext* context, const ::rocvad::MesgDeleteDevice& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rocvad::MesgNone>* PrepareAsyncdelete_deviceRaw(::grpc::ClientContext* context, const ::rocvad::MesgDeleteDevice& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ping_;
    const ::grpc::internal::RpcMethod rpcmethod_get_info_;
    const ::grpc::internal::RpcMethod rpcmethod_stream_logs_;
    const ::grpc::internal::RpcMethod rpcmethod_add_device_;
    const ::grpc::internal::RpcMethod rpcmethod_delete_device_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ping(::grpc::ServerContext* context, const ::rocvad::MesgNone* request, ::rocvad::MesgNone* response);
    virtual ::grpc::Status get_info(::grpc::ServerContext* context, const ::rocvad::MesgNone* request, ::rocvad::MesgInfo* response);
    virtual ::grpc::Status stream_logs(::grpc::ServerContext* context, const ::rocvad::MesgNone* request, ::grpc::ServerWriter< ::rocvad::MesgLogEntry>* writer);
    virtual ::grpc::Status add_device(::grpc::ServerContext* context, const ::rocvad::MesgAddDevice* request, ::rocvad::MesgNone* response);
    virtual ::grpc::Status delete_device(::grpc::ServerContext* context, const ::rocvad::MesgDeleteDevice* request, ::rocvad::MesgNone* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ping() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ping(::grpc::ServerContext* /*context*/, const ::rocvad::MesgNone* /*request*/, ::rocvad::MesgNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestping(::grpc::ServerContext* context, ::rocvad::MesgNone* request, ::grpc::ServerAsyncResponseWriter< ::rocvad::MesgNone>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_get_info : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_get_info() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_get_info() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_info(::grpc::ServerContext* /*context*/, const ::rocvad::MesgNone* /*request*/, ::rocvad::MesgInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestget_info(::grpc::ServerContext* context, ::rocvad::MesgNone* request, ::grpc::ServerAsyncResponseWriter< ::rocvad::MesgInfo>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_stream_logs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_stream_logs() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_stream_logs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status stream_logs(::grpc::ServerContext* /*context*/, const ::rocvad::MesgNone* /*request*/, ::grpc::ServerWriter< ::rocvad::MesgLogEntry>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requeststream_logs(::grpc::ServerContext* context, ::rocvad::MesgNone* request, ::grpc::ServerAsyncWriter< ::rocvad::MesgLogEntry>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(2, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_add_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_add_device() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_add_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status add_device(::grpc::ServerContext* /*context*/, const ::rocvad::MesgAddDevice* /*request*/, ::rocvad::MesgNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestadd_device(::grpc::ServerContext* context, ::rocvad::MesgAddDevice* request, ::grpc::ServerAsyncResponseWriter< ::rocvad::MesgNone>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_delete_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_delete_device() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_delete_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status delete_device(::grpc::ServerContext* /*context*/, const ::rocvad::MesgDeleteDevice* /*request*/, ::rocvad::MesgNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestdelete_device(::grpc::ServerContext* context, ::rocvad::MesgDeleteDevice* request, ::grpc::ServerAsyncResponseWriter< ::rocvad::MesgNone>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ping<WithAsyncMethod_get_info<WithAsyncMethod_stream_logs<WithAsyncMethod_add_device<WithAsyncMethod_delete_device<Service > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ping() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::rocvad::MesgNone, ::rocvad::MesgNone>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rocvad::MesgNone* request, ::rocvad::MesgNone* response) { return this->ping(context, request, response); }));}
    void SetMessageAllocatorFor_ping(
        ::grpc::MessageAllocator< ::rocvad::MesgNone, ::rocvad::MesgNone>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rocvad::MesgNone, ::rocvad::MesgNone>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ping(::grpc::ServerContext* /*context*/, const ::rocvad::MesgNone* /*request*/, ::rocvad::MesgNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ping(
      ::grpc::CallbackServerContext* /*context*/, const ::rocvad::MesgNone* /*request*/, ::rocvad::MesgNone* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_get_info : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_get_info() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::rocvad::MesgNone, ::rocvad::MesgInfo>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rocvad::MesgNone* request, ::rocvad::MesgInfo* response) { return this->get_info(context, request, response); }));}
    void SetMessageAllocatorFor_get_info(
        ::grpc::MessageAllocator< ::rocvad::MesgNone, ::rocvad::MesgInfo>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rocvad::MesgNone, ::rocvad::MesgInfo>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_get_info() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_info(::grpc::ServerContext* /*context*/, const ::rocvad::MesgNone* /*request*/, ::rocvad::MesgInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* get_info(
      ::grpc::CallbackServerContext* /*context*/, const ::rocvad::MesgNone* /*request*/, ::rocvad::MesgInfo* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_stream_logs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_stream_logs() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackServerStreamingHandler< ::rocvad::MesgNone, ::rocvad::MesgLogEntry>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rocvad::MesgNone* request) { return this->stream_logs(context, request); }));
    }
    ~WithCallbackMethod_stream_logs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status stream_logs(::grpc::ServerContext* /*context*/, const ::rocvad::MesgNone* /*request*/, ::grpc::ServerWriter< ::rocvad::MesgLogEntry>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::rocvad::MesgLogEntry>* stream_logs(
      ::grpc::CallbackServerContext* /*context*/, const ::rocvad::MesgNone* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_add_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_add_device() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::rocvad::MesgAddDevice, ::rocvad::MesgNone>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rocvad::MesgAddDevice* request, ::rocvad::MesgNone* response) { return this->add_device(context, request, response); }));}
    void SetMessageAllocatorFor_add_device(
        ::grpc::MessageAllocator< ::rocvad::MesgAddDevice, ::rocvad::MesgNone>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rocvad::MesgAddDevice, ::rocvad::MesgNone>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_add_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status add_device(::grpc::ServerContext* /*context*/, const ::rocvad::MesgAddDevice* /*request*/, ::rocvad::MesgNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* add_device(
      ::grpc::CallbackServerContext* /*context*/, const ::rocvad::MesgAddDevice* /*request*/, ::rocvad::MesgNone* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_delete_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_delete_device() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::rocvad::MesgDeleteDevice, ::rocvad::MesgNone>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rocvad::MesgDeleteDevice* request, ::rocvad::MesgNone* response) { return this->delete_device(context, request, response); }));}
    void SetMessageAllocatorFor_delete_device(
        ::grpc::MessageAllocator< ::rocvad::MesgDeleteDevice, ::rocvad::MesgNone>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rocvad::MesgDeleteDevice, ::rocvad::MesgNone>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_delete_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status delete_device(::grpc::ServerContext* /*context*/, const ::rocvad::MesgDeleteDevice* /*request*/, ::rocvad::MesgNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* delete_device(
      ::grpc::CallbackServerContext* /*context*/, const ::rocvad::MesgDeleteDevice* /*request*/, ::rocvad::MesgNone* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ping<WithCallbackMethod_get_info<WithCallbackMethod_stream_logs<WithCallbackMethod_add_device<WithCallbackMethod_delete_device<Service > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ping() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ping(::grpc::ServerContext* /*context*/, const ::rocvad::MesgNone* /*request*/, ::rocvad::MesgNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_get_info : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_get_info() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_get_info() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_info(::grpc::ServerContext* /*context*/, const ::rocvad::MesgNone* /*request*/, ::rocvad::MesgInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_stream_logs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_stream_logs() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_stream_logs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status stream_logs(::grpc::ServerContext* /*context*/, const ::rocvad::MesgNone* /*request*/, ::grpc::ServerWriter< ::rocvad::MesgLogEntry>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_add_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_add_device() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_add_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status add_device(::grpc::ServerContext* /*context*/, const ::rocvad::MesgAddDevice* /*request*/, ::rocvad::MesgNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_delete_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_delete_device() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_delete_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status delete_device(::grpc::ServerContext* /*context*/, const ::rocvad::MesgDeleteDevice* /*request*/, ::rocvad::MesgNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ping() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ping(::grpc::ServerContext* /*context*/, const ::rocvad::MesgNone* /*request*/, ::rocvad::MesgNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestping(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_get_info : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_get_info() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_get_info() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_info(::grpc::ServerContext* /*context*/, const ::rocvad::MesgNone* /*request*/, ::rocvad::MesgInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestget_info(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_stream_logs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_stream_logs() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_stream_logs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status stream_logs(::grpc::ServerContext* /*context*/, const ::rocvad::MesgNone* /*request*/, ::grpc::ServerWriter< ::rocvad::MesgLogEntry>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requeststream_logs(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(2, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_add_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_add_device() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_add_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status add_device(::grpc::ServerContext* /*context*/, const ::rocvad::MesgAddDevice* /*request*/, ::rocvad::MesgNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestadd_device(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_delete_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_delete_device() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_delete_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status delete_device(::grpc::ServerContext* /*context*/, const ::rocvad::MesgDeleteDevice* /*request*/, ::rocvad::MesgNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestdelete_device(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ping() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ping(context, request, response); }));
    }
    ~WithRawCallbackMethod_ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ping(::grpc::ServerContext* /*context*/, const ::rocvad::MesgNone* /*request*/, ::rocvad::MesgNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ping(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_get_info : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_get_info() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->get_info(context, request, response); }));
    }
    ~WithRawCallbackMethod_get_info() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_info(::grpc::ServerContext* /*context*/, const ::rocvad::MesgNone* /*request*/, ::rocvad::MesgInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* get_info(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_stream_logs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_stream_logs() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->stream_logs(context, request); }));
    }
    ~WithRawCallbackMethod_stream_logs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status stream_logs(::grpc::ServerContext* /*context*/, const ::rocvad::MesgNone* /*request*/, ::grpc::ServerWriter< ::rocvad::MesgLogEntry>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* stream_logs(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_add_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_add_device() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->add_device(context, request, response); }));
    }
    ~WithRawCallbackMethod_add_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status add_device(::grpc::ServerContext* /*context*/, const ::rocvad::MesgAddDevice* /*request*/, ::rocvad::MesgNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* add_device(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_delete_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_delete_device() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->delete_device(context, request, response); }));
    }
    ~WithRawCallbackMethod_delete_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status delete_device(::grpc::ServerContext* /*context*/, const ::rocvad::MesgDeleteDevice* /*request*/, ::rocvad::MesgNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* delete_device(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ping() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rocvad::MesgNone, ::rocvad::MesgNone>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rocvad::MesgNone, ::rocvad::MesgNone>* streamer) {
                       return this->Streamedping(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ping(::grpc::ServerContext* /*context*/, const ::rocvad::MesgNone* /*request*/, ::rocvad::MesgNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedping(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rocvad::MesgNone,::rocvad::MesgNone>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_get_info : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_get_info() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rocvad::MesgNone, ::rocvad::MesgInfo>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rocvad::MesgNone, ::rocvad::MesgInfo>* streamer) {
                       return this->Streamedget_info(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_get_info() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status get_info(::grpc::ServerContext* /*context*/, const ::rocvad::MesgNone* /*request*/, ::rocvad::MesgInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedget_info(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rocvad::MesgNone,::rocvad::MesgInfo>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_add_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_add_device() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rocvad::MesgAddDevice, ::rocvad::MesgNone>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rocvad::MesgAddDevice, ::rocvad::MesgNone>* streamer) {
                       return this->Streamedadd_device(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_add_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status add_device(::grpc::ServerContext* /*context*/, const ::rocvad::MesgAddDevice* /*request*/, ::rocvad::MesgNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedadd_device(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rocvad::MesgAddDevice,::rocvad::MesgNone>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_delete_device : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_delete_device() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rocvad::MesgDeleteDevice, ::rocvad::MesgNone>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rocvad::MesgDeleteDevice, ::rocvad::MesgNone>* streamer) {
                       return this->Streameddelete_device(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_delete_device() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status delete_device(::grpc::ServerContext* /*context*/, const ::rocvad::MesgDeleteDevice* /*request*/, ::rocvad::MesgNone* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streameddelete_device(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rocvad::MesgDeleteDevice,::rocvad::MesgNone>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ping<WithStreamedUnaryMethod_get_info<WithStreamedUnaryMethod_add_device<WithStreamedUnaryMethod_delete_device<Service > > > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_stream_logs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_stream_logs() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::rocvad::MesgNone, ::rocvad::MesgLogEntry>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::rocvad::MesgNone, ::rocvad::MesgLogEntry>* streamer) {
                       return this->Streamedstream_logs(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_stream_logs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status stream_logs(::grpc::ServerContext* /*context*/, const ::rocvad::MesgNone* /*request*/, ::grpc::ServerWriter< ::rocvad::MesgLogEntry>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status Streamedstream_logs(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::rocvad::MesgNone,::rocvad::MesgLogEntry>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_stream_logs<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_ping<WithStreamedUnaryMethod_get_info<WithSplitStreamingMethod_stream_logs<WithStreamedUnaryMethod_add_device<WithStreamedUnaryMethod_delete_device<Service > > > > > StreamedService;
};

}  // namespace rocvad


#endif  // GRPC_driver_5fprotocol_2eproto__INCLUDED
