// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: device_manager_protocol.proto

#include "device_manager_protocol.pb.h"
#include "device_manager_protocol.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace rcp {
namespace proto {

static const char* DeviceManagerProtocol_method_names[] = {
  "/rcp.proto.DeviceManagerProtocol/ping",
  "/rcp.proto.DeviceManagerProtocol/get_info",
  "/rcp.proto.DeviceManagerProtocol/add_device",
  "/rcp.proto.DeviceManagerProtocol/delete_device",
};

std::unique_ptr< DeviceManagerProtocol::Stub> DeviceManagerProtocol::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DeviceManagerProtocol::Stub> stub(new DeviceManagerProtocol::Stub(channel, options));
  return stub;
}

DeviceManagerProtocol::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ping_(DeviceManagerProtocol_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_get_info_(DeviceManagerProtocol_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_add_device_(DeviceManagerProtocol_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_delete_device_(DeviceManagerProtocol_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status DeviceManagerProtocol::Stub::ping(::grpc::ClientContext* context, const ::rcp::proto::None& request, ::rcp::proto::None* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rcp::proto::None, ::rcp::proto::None, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ping_, context, request, response);
}

void DeviceManagerProtocol::Stub::async::ping(::grpc::ClientContext* context, const ::rcp::proto::None* request, ::rcp::proto::None* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rcp::proto::None, ::rcp::proto::None, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ping_, context, request, response, std::move(f));
}

void DeviceManagerProtocol::Stub::async::ping(::grpc::ClientContext* context, const ::rcp::proto::None* request, ::rcp::proto::None* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ping_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rcp::proto::None>* DeviceManagerProtocol::Stub::PrepareAsyncpingRaw(::grpc::ClientContext* context, const ::rcp::proto::None& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rcp::proto::None, ::rcp::proto::None, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ping_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rcp::proto::None>* DeviceManagerProtocol::Stub::AsyncpingRaw(::grpc::ClientContext* context, const ::rcp::proto::None& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncpingRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DeviceManagerProtocol::Stub::get_info(::grpc::ClientContext* context, const ::rcp::proto::None& request, ::rcp::proto::Info* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rcp::proto::None, ::rcp::proto::Info, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_get_info_, context, request, response);
}

void DeviceManagerProtocol::Stub::async::get_info(::grpc::ClientContext* context, const ::rcp::proto::None* request, ::rcp::proto::Info* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rcp::proto::None, ::rcp::proto::Info, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_get_info_, context, request, response, std::move(f));
}

void DeviceManagerProtocol::Stub::async::get_info(::grpc::ClientContext* context, const ::rcp::proto::None* request, ::rcp::proto::Info* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_get_info_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rcp::proto::Info>* DeviceManagerProtocol::Stub::PrepareAsyncget_infoRaw(::grpc::ClientContext* context, const ::rcp::proto::None& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rcp::proto::Info, ::rcp::proto::None, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_get_info_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rcp::proto::Info>* DeviceManagerProtocol::Stub::Asyncget_infoRaw(::grpc::ClientContext* context, const ::rcp::proto::None& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncget_infoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DeviceManagerProtocol::Stub::add_device(::grpc::ClientContext* context, const ::rcp::proto::AddDeviceArgs& request, ::rcp::proto::None* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rcp::proto::AddDeviceArgs, ::rcp::proto::None, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_add_device_, context, request, response);
}

void DeviceManagerProtocol::Stub::async::add_device(::grpc::ClientContext* context, const ::rcp::proto::AddDeviceArgs* request, ::rcp::proto::None* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rcp::proto::AddDeviceArgs, ::rcp::proto::None, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_add_device_, context, request, response, std::move(f));
}

void DeviceManagerProtocol::Stub::async::add_device(::grpc::ClientContext* context, const ::rcp::proto::AddDeviceArgs* request, ::rcp::proto::None* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_add_device_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rcp::proto::None>* DeviceManagerProtocol::Stub::PrepareAsyncadd_deviceRaw(::grpc::ClientContext* context, const ::rcp::proto::AddDeviceArgs& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rcp::proto::None, ::rcp::proto::AddDeviceArgs, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_add_device_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rcp::proto::None>* DeviceManagerProtocol::Stub::Asyncadd_deviceRaw(::grpc::ClientContext* context, const ::rcp::proto::AddDeviceArgs& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncadd_deviceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DeviceManagerProtocol::Stub::delete_device(::grpc::ClientContext* context, const ::rcp::proto::DeleteDeviceArgs& request, ::rcp::proto::None* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rcp::proto::DeleteDeviceArgs, ::rcp::proto::None, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_delete_device_, context, request, response);
}

void DeviceManagerProtocol::Stub::async::delete_device(::grpc::ClientContext* context, const ::rcp::proto::DeleteDeviceArgs* request, ::rcp::proto::None* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rcp::proto::DeleteDeviceArgs, ::rcp::proto::None, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_delete_device_, context, request, response, std::move(f));
}

void DeviceManagerProtocol::Stub::async::delete_device(::grpc::ClientContext* context, const ::rcp::proto::DeleteDeviceArgs* request, ::rcp::proto::None* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_delete_device_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rcp::proto::None>* DeviceManagerProtocol::Stub::PrepareAsyncdelete_deviceRaw(::grpc::ClientContext* context, const ::rcp::proto::DeleteDeviceArgs& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rcp::proto::None, ::rcp::proto::DeleteDeviceArgs, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_delete_device_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rcp::proto::None>* DeviceManagerProtocol::Stub::Asyncdelete_deviceRaw(::grpc::ClientContext* context, const ::rcp::proto::DeleteDeviceArgs& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdelete_deviceRaw(context, request, cq);
  result->StartCall();
  return result;
}

DeviceManagerProtocol::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DeviceManagerProtocol_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DeviceManagerProtocol::Service, ::rcp::proto::None, ::rcp::proto::None, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DeviceManagerProtocol::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rcp::proto::None* req,
             ::rcp::proto::None* resp) {
               return service->ping(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DeviceManagerProtocol_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DeviceManagerProtocol::Service, ::rcp::proto::None, ::rcp::proto::Info, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DeviceManagerProtocol::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rcp::proto::None* req,
             ::rcp::proto::Info* resp) {
               return service->get_info(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DeviceManagerProtocol_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DeviceManagerProtocol::Service, ::rcp::proto::AddDeviceArgs, ::rcp::proto::None, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DeviceManagerProtocol::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rcp::proto::AddDeviceArgs* req,
             ::rcp::proto::None* resp) {
               return service->add_device(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DeviceManagerProtocol_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DeviceManagerProtocol::Service, ::rcp::proto::DeleteDeviceArgs, ::rcp::proto::None, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DeviceManagerProtocol::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rcp::proto::DeleteDeviceArgs* req,
             ::rcp::proto::None* resp) {
               return service->delete_device(ctx, req, resp);
             }, this)));
}

DeviceManagerProtocol::Service::~Service() {
}

::grpc::Status DeviceManagerProtocol::Service::ping(::grpc::ServerContext* context, const ::rcp::proto::None* request, ::rcp::proto::None* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DeviceManagerProtocol::Service::get_info(::grpc::ServerContext* context, const ::rcp::proto::None* request, ::rcp::proto::Info* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DeviceManagerProtocol::Service::add_device(::grpc::ServerContext* context, const ::rcp::proto::AddDeviceArgs* request, ::rcp::proto::None* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DeviceManagerProtocol::Service::delete_device(::grpc::ServerContext* context, const ::rcp::proto::DeleteDeviceArgs* request, ::rcp::proto::None* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace rcp
}  // namespace proto

