// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device_manager_protocol.proto

#include "device_manager_protocol.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace rcp {
namespace proto {
PROTOBUF_CONSTEXPR None::None(
    ::_pbi::ConstantInitialized) {}
struct NoneDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NoneDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~NoneDefaultTypeInternal() {}
  union {
    None _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NoneDefaultTypeInternal _None_default_instance_;
PROTOBUF_CONSTEXPR AddDeviceArgs::AddDeviceArgs(
    ::_pbi::ConstantInitialized) {}
struct AddDeviceArgsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AddDeviceArgsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AddDeviceArgsDefaultTypeInternal() {}
  union {
    AddDeviceArgs _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AddDeviceArgsDefaultTypeInternal _AddDeviceArgs_default_instance_;
PROTOBUF_CONSTEXPR RemoveDeviceArgs::RemoveDeviceArgs(
    ::_pbi::ConstantInitialized) {}
struct RemoveDeviceArgsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RemoveDeviceArgsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RemoveDeviceArgsDefaultTypeInternal() {}
  union {
    RemoveDeviceArgs _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RemoveDeviceArgsDefaultTypeInternal _RemoveDeviceArgs_default_instance_;
}  // namespace proto
}  // namespace rcp
static ::_pb::Metadata file_level_metadata_device_5fmanager_5fprotocol_2eproto[3];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_device_5fmanager_5fprotocol_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_device_5fmanager_5fprotocol_2eproto = nullptr;

const uint32_t TableStruct_device_5fmanager_5fprotocol_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::rcp::proto::None, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::rcp::proto::AddDeviceArgs, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::rcp::proto::RemoveDeviceArgs, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::rcp::proto::None)},
  { 6, -1, -1, sizeof(::rcp::proto::AddDeviceArgs)},
  { 12, -1, -1, sizeof(::rcp::proto::RemoveDeviceArgs)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::rcp::proto::_None_default_instance_._instance,
  &::rcp::proto::_AddDeviceArgs_default_instance_._instance,
  &::rcp::proto::_RemoveDeviceArgs_default_instance_._instance,
};

const char descriptor_table_protodef_device_5fmanager_5fprotocol_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\035device_manager_protocol.proto\022\trcp.pro"
  "to\"\006\n\004None\"\017\n\rAddDeviceArgs\"\022\n\020RemoveDev"
  "iceArgs2\277\001\n\025DeviceManagerProtocol\022*\n\004pin"
  "g\022\017.rcp.proto.None\032\017.rcp.proto.None\"\000\0229\n"
  "\nadd_device\022\030.rcp.proto.AddDeviceArgs\032\017."
  "rcp.proto.None\"\000\022\?\n\rremove_device\022\033.rcp."
  "proto.RemoveDeviceArgs\032\017.rcp.proto.None\""
  "\000b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_device_5fmanager_5fprotocol_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_device_5fmanager_5fprotocol_2eproto = {
    false, false, 289, descriptor_table_protodef_device_5fmanager_5fprotocol_2eproto,
    "device_manager_protocol.proto",
    &descriptor_table_device_5fmanager_5fprotocol_2eproto_once, nullptr, 0, 3,
    schemas, file_default_instances, TableStruct_device_5fmanager_5fprotocol_2eproto::offsets,
    file_level_metadata_device_5fmanager_5fprotocol_2eproto, file_level_enum_descriptors_device_5fmanager_5fprotocol_2eproto,
    file_level_service_descriptors_device_5fmanager_5fprotocol_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_device_5fmanager_5fprotocol_2eproto_getter() {
  return &descriptor_table_device_5fmanager_5fprotocol_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_device_5fmanager_5fprotocol_2eproto(&descriptor_table_device_5fmanager_5fprotocol_2eproto);
namespace rcp {
namespace proto {

// ===================================================================

class None::_Internal {
 public:
};

None::None(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:rcp.proto.None)
}
None::None(const None& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  None* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:rcp.proto.None)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData None::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*None::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata None::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_device_5fmanager_5fprotocol_2eproto_getter, &descriptor_table_device_5fmanager_5fprotocol_2eproto_once,
      file_level_metadata_device_5fmanager_5fprotocol_2eproto[0]);
}

// ===================================================================

class AddDeviceArgs::_Internal {
 public:
};

AddDeviceArgs::AddDeviceArgs(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:rcp.proto.AddDeviceArgs)
}
AddDeviceArgs::AddDeviceArgs(const AddDeviceArgs& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  AddDeviceArgs* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:rcp.proto.AddDeviceArgs)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AddDeviceArgs::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AddDeviceArgs::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata AddDeviceArgs::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_device_5fmanager_5fprotocol_2eproto_getter, &descriptor_table_device_5fmanager_5fprotocol_2eproto_once,
      file_level_metadata_device_5fmanager_5fprotocol_2eproto[1]);
}

// ===================================================================

class RemoveDeviceArgs::_Internal {
 public:
};

RemoveDeviceArgs::RemoveDeviceArgs(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:rcp.proto.RemoveDeviceArgs)
}
RemoveDeviceArgs::RemoveDeviceArgs(const RemoveDeviceArgs& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  RemoveDeviceArgs* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:rcp.proto.RemoveDeviceArgs)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RemoveDeviceArgs::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RemoveDeviceArgs::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata RemoveDeviceArgs::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_device_5fmanager_5fprotocol_2eproto_getter, &descriptor_table_device_5fmanager_5fprotocol_2eproto_once,
      file_level_metadata_device_5fmanager_5fprotocol_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace rcp
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::rcp::proto::None*
Arena::CreateMaybeMessage< ::rcp::proto::None >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rcp::proto::None >(arena);
}
template<> PROTOBUF_NOINLINE ::rcp::proto::AddDeviceArgs*
Arena::CreateMaybeMessage< ::rcp::proto::AddDeviceArgs >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rcp::proto::AddDeviceArgs >(arena);
}
template<> PROTOBUF_NOINLINE ::rcp::proto::RemoveDeviceArgs*
Arena::CreateMaybeMessage< ::rcp::proto::RemoveDeviceArgs >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rcp::proto::RemoveDeviceArgs >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
