name: "build"

on:
  push:
    branches:
      - main
      - v*
    tags:
      - v*

  pull_request:

  repository_dispatch:
    types:
      - trigger_build

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * 1'

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        macos: [latest, 15, 14, 13]

    runs-on: macos-${{ matrix.macos }}
    name: macos-${{ matrix.macos }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: tecolicom/actions-use-homebrew-tools@v1
        with:
          tools: scons autoconf automake pkg-config libtool go

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Build
        run: |
          make

      - name: Test
        run: |
          make test

      - name: Install
        run: |
          sudo make install

  release:
    needs: [build]
    if: |
      github.repository_owner == 'roc-streaming' &&
      github.event_name == 'push' &&
      startsWith(github.ref, 'refs/tags/v')

    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: tecolicom/actions-use-homebrew-tools@v1
        with:
          tools: scons autoconf automake pkg-config libtool go

      - name: Build
        run: |
          make

      - name: Create tarball
        run: |
          make dist

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: roc-vad.tar.bz2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
