name: "build"

on:
  push:
    branches:
      - main

  pull_request:

  repository_dispatch:
    types:
      - trigger_build

  workflow_dispatch:
  workflow_call:

  schedule:
    - cron: '0 0 * * 1'

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        macos: [latest, 15, 14, 13]

    runs-on: macos-${{ matrix.macos }}
    name: build/macos-${{ matrix.macos }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: tecolicom/actions-use-homebrew-tools@v1
        with:
          tools: scons autoconf automake pkg-config libtool go

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Build
        run: |
          make

      - name: Test
        run: |
          make test

      - name: Check
        run: |
          bin/roc-vad --help

  install-make:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: tecolicom/actions-use-homebrew-tools@v1
        with:
          tools: scons autoconf automake pkg-config libtool go

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Build
        run: |
          make

      - name: Install
        run: |
          sudo make install

      - name: Check
        run: |
          [ -e /usr/local/bin/roc-vad ]
          [ -e /Library/Audio/Plug-Ins/HAL/roc_vad.driver ]
          /usr/local/bin/roc-vad --help

      - name: Uninstall
        run: |
          sudo make uninstall

      - name: Check
        run: |
          [ ! -e /usr/local/bin/roc-vad ]
          [ ! -e /Library/Audio/Plug-Ins/HAL/roc_vad.driver ]

  install-dist:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: tecolicom/actions-use-homebrew-tools@v1
        with:
          tools: scons autoconf automake pkg-config libtool go

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Build
        run: |
          make

      - name: Dist
        run: |
          make dist

      - name: Install
        run: |
          sudo ./install.sh roc-vad.tar.bz2

      - name: Check
        run: |
          [ -e /usr/local/bin/roc-vad ]
          [ -e /Library/Audio/Plug-Ins/HAL/roc_vad.driver ]
          /usr/local/bin/roc-vad --help

      - name: Uninstall
        run: |
          sudo /usr/local/bin/roc-vad uninstall

      - name: Check
        run: |
          [ ! -e /usr/local/bin/roc-vad ]
          [ ! -e /Library/Audio/Plug-Ins/HAL/roc_vad.driver ]
