name: "pr_closed"

on:
  repository_dispatch:
    types:
      - pull_request_closed

permissions:
  pull-requests: write

concurrency:
  group: pullreq-${{ github.event.client_payload.number }}

jobs:
  main:
    uses: roc-streaming/ci/.github/workflows/pr_status_closed.yml@main
    with:
      pr-number: ${{ github.event.client_payload.number }}
    secrets:
      triage-token: ${{ secrets.REPO_TRIAGE }}
